/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createErrorModelFromDiscriminatorValue, serializeUpdateJobLimitRequestBody, type ErrorModel, type UpdateJobLimitRequestBody } from '../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/jobs/{id}/actions/update-limit
 */
export interface UpdateLimitRequestBuilder extends BaseRequestBuilder<UpdateLimitRequestBuilder> {
    /**
     * Post API jobs by ID actions update limit
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @throws {ErrorModel} error when the service returns a 4XX or 5XX status code
     */
     post(body: UpdateJobLimitRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * Post API jobs by ID actions update limit
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: UpdateJobLimitRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const UpdateLimitRequestBuilderUriTemplate = "{+baseurl}/api/jobs/{id}/actions/update-limit";
/**
 * Metadata for all the requests in the request builder.
 */
export const UpdateLimitRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: UpdateLimitRequestBuilderUriTemplate,
        responseBodyContentType: "application/problem+json",
        errorMappings: {
            XXX: createErrorModelFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendNoResponseContent",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeUpdateJobLimitRequestBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
