version: '3'

interval: '500ms'

vars:
  GO_EXTRACTOR_DEV_SERVER_PORT: 8080
  GO_EXTRACTOR_DEV_CLIENT_PORT: 4200

tasks:

  # Basic development related tasks

  dev:
    deps:
    - server:dev
    - client:dev

  server:dev:
    cmds:
    - go run . serve -p {{.GO_EXTRACTOR_DEV_SERVER_PORT}}

  client:dev:
    dir: web
    cmds:
    - NG_APP_API_URL=http://localhost:{{.GO_EXTRACTOR_DEV_SERVER_PORT}}/api npm run start -- --port {{.GO_EXTRACTOR_DEV_CLIENT_PORT}}

  client:dev:build:
    dir: web
    sources:
    - web/src/**/*
    cmds:
    - npm run build:dev

  preview:
    deps: ['client:dev:build']
    cmds:
    - task: start

  # Advanced development related tasks

  install-sqlc:
    cmds:
    - go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
    status:
    - sqlc --help
  install-migrate:
    status:
    - migrate -version
    cmds:
    - go install -tags 'sqlite3' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

  install-dev-deps:
    deps: [install-sqlc, install-migrate]

  sql-watch:
    deps: [install-sqlc]
    watch: true
    sources:
    - db/migrations/*.sql
    - db/queries/*.sql
    generates:
    - db/db.go
    - db/models.go
    - db/*.sql.go
    cmds:
    - sqlc generate

  generate-migration:
    deps: [install-migrate]
    dir: db/migrations
    preconditions:
    - sh: test -n "{{.CLI_ARGS}}"
      msg: "Please provide a name for the migration"
    cmds:
    - migrate create -ext sql {{.CLI_ARGS}}

  delete-last-migration:
    dir: db/migrations
    cmds:
    - rm -f $(ls -t | head -n2)

  redo-last-migration:
    dir: db/migrations
    deps: [delete-last-migration]
    preconditions:
    - sh: test -n "{{.CLI_ARGS}}"
      msg: "Please provide a name for the migration"
    cmds:
    - task: generate-migration

  # Production related tasks

  client:prod:build:
    dir: web
    sources:
    - web/src/**/*
    cmds:
    - npm run build

  docker:new-builder:
    cmds:
    - docker buildx create --name builderx --use

  docker:build-docker:
    cmds:
    - docker buildx build --platform linux/amd64 -t vkhobor/extractor:latest --pull --push .

  docker:rebuild-docker:
    cmds:
    - docker buildx build --platform linux/amd64  --no-cache -t vkhobor/extractor:latest --pull --load .
