/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createErrorModelFromDiscriminatorValue, createJobDetailsFromDiscriminatorValue, type ErrorModel, type JobDetails } from '../../../models/';
// @ts-ignore
import { type VideosRequestBuilder, VideosRequestBuilderRequestsMetadata } from './videos/';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/jobs/{id}
 */
export interface JobsItemRequestBuilder extends BaseRequestBuilder<JobsItemRequestBuilder> {
    /**
     * The videos property
     */
    get videos(): VideosRequestBuilder;
    /**
     * Get API jobs by ID
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<JobDetails>}
     * @throws {ErrorModel} error when the service returns a 4XX or 5XX status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<JobDetails | undefined>;
    /**
     * Get API jobs by ID
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const JobsItemRequestBuilderUriTemplate = "{+baseurl}/api/jobs/{id}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const JobsItemRequestBuilderNavigationMetadata: Record<Exclude<keyof JobsItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    videos: {
        requestsMetadata: VideosRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const JobsItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: JobsItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createErrorModelFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createJobDetailsFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
