/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import {
    ImagesRequestBuilderRequestsMetadata,
    type ImagesRequestBuilder,
} from './images/index.js';
// @ts-ignore
import {
    JobsRequestBuilderNavigationMetadata,
    JobsRequestBuilderRequestsMetadata,
    type JobsRequestBuilder,
} from './jobs/index.js';
// @ts-ignore
import {
    type BaseRequestBuilder,
    type KeysToExcludeForNavigationMetadata,
    type NavigationMetadata,
} from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api
 */
export interface ApiRequestBuilder
    extends BaseRequestBuilder<ApiRequestBuilder> {
    /**
     * The images property
     */
    get images(): ImagesRequestBuilder;
    /**
     * The jobs property
     */
    get jobs(): JobsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ApiRequestBuilderUriTemplate = '{+baseurl}/api';
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ApiRequestBuilderNavigationMetadata: Record<
    Exclude<keyof ApiRequestBuilder, KeysToExcludeForNavigationMetadata>,
    NavigationMetadata
> = {
    images: {
        requestsMetadata: ImagesRequestBuilderRequestsMetadata,
    },
    jobs: {
        requestsMetadata: JobsRequestBuilderRequestsMetadata,
        navigationMetadata: JobsRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
