// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: downloads.sql

package db

import (
	"context"
	"database/sql"
)

const addDownloadAttempt = `-- name: AddDownloadAttempt :exec
INSERT INTO
  download_attempts (id, yt_video_id, error, blob_storage_id, progress)
VALUES
  (?, ?, ?, ?, ?)
`

type AddDownloadAttemptParams struct {
	ID            string
	YtVideoID     sql.NullString
	Error         sql.NullString
	BlobStorageID sql.NullString
	Progress      sql.NullInt64
}

func (q *Queries) AddDownloadAttempt(ctx context.Context, arg AddDownloadAttemptParams) error {
	_, err := q.db.ExecContext(ctx, addDownloadAttempt,
		arg.ID,
		arg.YtVideoID,
		arg.Error,
		arg.BlobStorageID,
		arg.Progress,
	)
	return err
}
