// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: downloads.sql

package db

import (
	"context"
	"database/sql"
)

const addDownloadAttempt = `-- name: AddDownloadAttempt :one

INSERT INTO download_attempts (
  yt_video_id, error, blob_storage_id, progress
) VALUES (
  ?, ?,?,?
)
RETURNING id, yt_video_id, progress, blob_storage_id, error
`

type AddDownloadAttemptParams struct {
	YtVideoID     sql.NullString
	Error         sql.NullString
	BlobStorageID sql.NullString
	Progress      sql.NullInt64
}

func (q *Queries) AddDownloadAttempt(ctx context.Context, arg AddDownloadAttemptParams) (DownloadAttempt, error) {
	row := q.db.QueryRowContext(ctx, addDownloadAttempt,
		arg.YtVideoID,
		arg.Error,
		arg.BlobStorageID,
		arg.Progress,
	)
	var i DownloadAttempt
	err := row.Scan(
		&i.ID,
		&i.YtVideoID,
		&i.Progress,
		&i.BlobStorageID,
		&i.Error,
	)
	return i, err
}
