// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: import.sql

package db

import (
	"context"
	"database/sql"
)

const addImportAttempt = `-- name: AddImportAttempt :one
INSERT INTO import_attempts (
  id, yt_video_id, filter_id, progress, error
) VALUES (
  ?, ?, ?, ?, ?
) RETURNING id, yt_video_id, filter_id, progress, error
`

type AddImportAttemptParams struct {
	ID        string
	YtVideoID sql.NullString
	FilterID  sql.NullString
	Progress  sql.NullInt64
	Error     sql.NullString
}

func (q *Queries) AddImportAttempt(ctx context.Context, arg AddImportAttemptParams) (ImportAttempt, error) {
	row := q.db.QueryRowContext(ctx, addImportAttempt,
		arg.ID,
		arg.YtVideoID,
		arg.FilterID,
		arg.Progress,
		arg.Error,
	)
	var i ImportAttempt
	err := row.Scan(
		&i.ID,
		&i.YtVideoID,
		&i.FilterID,
		&i.Progress,
		&i.Error,
	)
	return i, err
}
