// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
)

type BlobStorage struct {
	ID   string
	Path string
}

type DownloadAttempt struct {
	ID            string
	YtVideoID     sql.NullString
	Progress      sql.NullInt64
	BlobStorageID sql.NullString
	Error         sql.NullString
}

type Filter struct {
	ID   string
	Name sql.NullString
}

type FilterImage struct {
	FilterID      sql.NullString
	BlobStorageID sql.NullString
}

type ImportAttempt struct {
	ID        string
	YtVideoID sql.NullString
	FilterID  sql.NullString
	Progress  sql.NullInt64
	Error     sql.NullString
}

type Job struct {
	ID          string
	SearchQuery sql.NullString
	FilterID    sql.NullString
	YoutubeID   sql.NullString
	Limit       sql.NullInt64
}

type Picture struct {
	ID              string
	ImportAttemptID sql.NullString
	FrameNumber     sql.NullInt64
	BlobStorageID   sql.NullString
}

type YtVideo struct {
	ID    string
	Name  sql.NullString
	JobID sql.NullString
}
