// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddBlob(ctx context.Context, arg AddBlobParams) error
	AddDownloadAttempt(ctx context.Context, arg AddDownloadAttemptParams) error
	AddFilter(ctx context.Context, arg AddFilterParams) (Filter, error)
	AddImportAttempt(ctx context.Context, arg AddImportAttemptParams) (ImportAttempt, error)
	AddPicture(ctx context.Context, arg AddPictureParams) error
	AddYtVideo(ctx context.Context, arg AddYtVideoParams) (YtVideo, error)
	AllPicturesCount(ctx context.Context, arg AllPicturesCountParams) (int64, error)
	AttachImageToFilter(ctx context.Context, arg AttachImageToFilterParams) (FilterImage, error)
	CreateJob(ctx context.Context, arg CreateJobParams) (Job, error)
	DeleteImagesOnFilter(ctx context.Context, filterID sql.NullString) error
	GetBlob(ctx context.Context, id string) (string, error)
	GetFilterById(ctx context.Context, id string) ([]GetFilterByIdRow, error)
	GetFilterForJob(ctx context.Context, id string) ([]GetFilterForJobRow, error)
	GetFilters(ctx context.Context) ([]GetFiltersRow, error)
	GetJob(ctx context.Context, id string) (GetJobRow, error)
	GetPictures(ctx context.Context, arg GetPicturesParams) ([]GetPicturesRow, error)
	GetScrapedVideos(ctx context.Context) ([]GetScrapedVideosRow, error)
	GetVideoWithDownloadAttempts(ctx context.Context, id string) ([]GetVideoWithDownloadAttemptsRow, error)
	GetVideoWithImportAttempts(ctx context.Context, id string) ([]GetVideoWithImportAttemptsRow, error)
	GetVideosDownloaded(ctx context.Context) ([]GetVideosDownloadedRow, error)
	GetVideosDownloadedButNotImported(ctx context.Context) ([]GetVideosDownloadedButNotImportedRow, error)
	GetYtVideoWithJob(ctx context.Context, id string) (GetYtVideoWithJobRow, error)
	UpdateImportAttemptError(ctx context.Context, arg UpdateImportAttemptErrorParams) error
	UpdateImportAttemptProgress(ctx context.Context, arg UpdateImportAttemptProgressParams) error
}

var _ Querier = (*Queries)(nil)
