/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createUntypedNodeFromDiscriminatorValue, type ApiError, type Parsable, type ParseNode, type SerializationWriter, UntypedNode } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreatedJob}
 */
export function createCreatedJobFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreatedJob;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreateJob}
 */
export function createCreateJobFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreateJob;
}
export interface CreatedJob extends Parsable {
    /**
     * The id property
     */
    id?: string;
    /**
     * A URL to the JSON Schema for this object.
     */
    schema?: string;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ErrorDetail}
 */
export function createErrorDetailFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoErrorDetail;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ErrorModel}
 */
export function createErrorModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoErrorModel;
}
export interface CreateJob extends Parsable {
    /**
     * The filter_id property
     */
    filter_id?: string;
    /**
     * The limit property
     */
    limit?: number;
    /**
     * A URL to the JSON Schema for this object.
     */
    schema?: string;
    /**
     * The search_query property
     */
    search_query?: string;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {JobAndVideos}
 */
export function createJobAndVideosFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoJobAndVideos;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {JobDetails}
 */
export function createJobDetailsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoJobDetails;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {JobVideo}
 */
export function createJobVideoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoJobVideo;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ListJobResponse}
 */
export function createListJobResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoListJobResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Picture}
 */
export function createPictureFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPicture;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Response}
 */
export function createResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UpdateJobLimitRequestBody}
 */
export function createUpdateJobLimitRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUpdateJobLimitRequestBody;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
export function deserializeIntoCreatedJob(createdJob: Partial<CreatedJob> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { createdJob.id = n.getStringValue(); },
        "$schema": n => { createdJob.schema = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
export function deserializeIntoCreateJob(createJob: Partial<CreateJob> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "filter_id": n => { createJob.filter_id = n.getStringValue(); },
        "limit": n => { createJob.limit = n.getNumberValue(); },
        "$schema": n => { createJob.schema = n.getStringValue(); },
        "search_query": n => { createJob.search_query = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
export function deserializeIntoErrorDetail(errorDetail: Partial<ErrorDetail> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "location": n => { errorDetail.location = n.getStringValue(); },
        "message": n => { errorDetail.message = n.getStringValue(); },
        "value": n => { errorDetail.value = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
export function deserializeIntoErrorModel(errorModel: Partial<ErrorModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "detail": n => { errorModel.detail = n.getStringValue(); },
        "errors": n => { errorModel.errors = n.getCollectionOfObjectValues<ErrorDetail>(createErrorDetailFromDiscriminatorValue); },
        "instance": n => { errorModel.instance = n.getStringValue(); },
        "$schema": n => { errorModel.schema = n.getStringValue(); },
        "status": n => { errorModel.status = n.getNumberValue(); },
        "title": n => { errorModel.title = n.getStringValue(); },
        "type": n => { errorModel.type = n.getStringValue() ?? "about:blank"; },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
export function deserializeIntoJobAndVideos(jobAndVideos: Partial<JobAndVideos> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { jobAndVideos.id = n.getStringValue(); },
        "$schema": n => { jobAndVideos.schema = n.getStringValue(); },
        "videos": n => { jobAndVideos.videos = n.getCollectionOfObjectValues<JobVideo>(createJobVideoFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
export function deserializeIntoJobDetails(jobDetails: Partial<JobDetails> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { jobDetails.id = n.getStringValue(); },
        "$schema": n => { jobDetails.schema = n.getStringValue(); },
        "search_query": n => { jobDetails.search_query = n.getStringValue(); },
        "videos_found": n => { jobDetails.videos_found = n.getNumberValue(); },
        "video_target": n => { jobDetails.video_target = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
export function deserializeIntoJobVideo(jobVideo: Partial<JobVideo> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "download_status": n => { jobVideo.download_status = n.getStringValue(); },
        "import_status": n => { jobVideo.import_status = n.getStringValue(); },
        "youtube_id": n => { jobVideo.youtube_id = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
export function deserializeIntoListJobResponse(listJobResponse: Partial<ListJobResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { listJobResponse.id = n.getStringValue(); },
        "limit": n => { listJobResponse.limit = n.getNumberValue(); },
        "search_query": n => { listJobResponse.search_query = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
export function deserializeIntoPicture(picture: Partial<Picture> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "blob_id": n => { picture.blob_id = n.getStringValue(); },
        "id": n => { picture.id = n.getStringValue(); },
        "youtube_id": n => { picture.youtube_id = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
export function deserializeIntoResponse(response: Partial<Response> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "pictures": n => { response.pictures = n.getCollectionOfObjectValues<Picture>(createPictureFromDiscriminatorValue); },
        "$schema": n => { response.schema = n.getStringValue(); },
        "total": n => { response.total = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
export function deserializeIntoUpdateJobLimitRequestBody(updateJobLimitRequestBody: Partial<UpdateJobLimitRequestBody> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "limit": n => { updateJobLimitRequestBody.limit = n.getNumberValue(); },
        "$schema": n => { updateJobLimitRequestBody.schema = n.getStringValue(); },
    }
}
export interface ErrorDetail extends Parsable {
    /**
     * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
     */
    location?: string;
    /**
     * Error message text
     */
    message?: string;
    /**
     * The value at the given location
     */
    value?: UntypedNode;
}
export interface ErrorModel extends ApiError, Parsable {
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: ErrorDetail[];
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * A URL to the JSON Schema for this object.
     */
    schema?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
}
export interface JobAndVideos extends Parsable {
    /**
     * The id property
     */
    id?: string;
    /**
     * A URL to the JSON Schema for this object.
     */
    schema?: string;
    /**
     * The videos property
     */
    videos?: JobVideo[];
}
export interface JobDetails extends Parsable {
    /**
     * The id property
     */
    id?: string;
    /**
     * A URL to the JSON Schema for this object.
     */
    schema?: string;
    /**
     * The search_query property
     */
    search_query?: string;
    /**
     * The video_target property
     */
    video_target?: number;
    /**
     * The videos_found property
     */
    videos_found?: number;
}
export interface JobVideo extends Parsable {
    /**
     * The download_status property
     */
    download_status?: string;
    /**
     * The import_status property
     */
    import_status?: string;
    /**
     * The youtube_id property
     */
    youtube_id?: string;
}
export interface ListJobResponse extends Parsable {
    /**
     * The id property
     */
    id?: string;
    /**
     * The limit property
     */
    limit?: number;
    /**
     * The search_query property
     */
    search_query?: string;
}
export interface Picture extends Parsable {
    /**
     * The blob_id property
     */
    blob_id?: string;
    /**
     * The id property
     */
    id?: string;
    /**
     * The youtube_id property
     */
    youtube_id?: string;
}
export interface Response extends Parsable {
    /**
     * The pictures property
     */
    pictures?: Picture[];
    /**
     * A URL to the JSON Schema for this object.
     */
    schema?: string;
    /**
     * The total property
     */
    total?: number;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
export function serializeCreatedJob(writer: SerializationWriter, createdJob: Partial<CreatedJob> | undefined = {}) : void {
    writer.writeStringValue("id", createdJob.id);
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
export function serializeCreateJob(writer: SerializationWriter, createJob: Partial<CreateJob> | undefined = {}) : void {
    writer.writeStringValue("filter_id", createJob.filter_id);
    writer.writeNumberValue("limit", createJob.limit);
    writer.writeStringValue("search_query", createJob.search_query);
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
export function serializeErrorDetail(writer: SerializationWriter, errorDetail: Partial<ErrorDetail> | undefined = {}) : void {
    writer.writeStringValue("location", errorDetail.location);
    writer.writeStringValue("message", errorDetail.message);
    writer.writeObjectValue("value", errorDetail.value);
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
export function serializeErrorModel(writer: SerializationWriter, errorModel: Partial<ErrorModel> | undefined = {}) : void {
    writer.writeStringValue("detail", errorModel.detail);
    writer.writeCollectionOfObjectValues<ErrorDetail>("errors", errorModel.errors, serializeErrorDetail);
    writer.writeStringValue("instance", errorModel.instance);
    writer.writeNumberValue("status", errorModel.status);
    writer.writeStringValue("title", errorModel.title);
    writer.writeStringValue("type", errorModel.type ?? "about:blank");
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
export function serializeJobAndVideos(writer: SerializationWriter, jobAndVideos: Partial<JobAndVideos> | undefined = {}) : void {
    writer.writeStringValue("id", jobAndVideos.id);
    writer.writeCollectionOfObjectValues<JobVideo>("videos", jobAndVideos.videos, serializeJobVideo);
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
export function serializeJobDetails(writer: SerializationWriter, jobDetails: Partial<JobDetails> | undefined = {}) : void {
    writer.writeStringValue("id", jobDetails.id);
    writer.writeStringValue("search_query", jobDetails.search_query);
    writer.writeNumberValue("videos_found", jobDetails.videos_found);
    writer.writeNumberValue("video_target", jobDetails.video_target);
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
export function serializeJobVideo(writer: SerializationWriter, jobVideo: Partial<JobVideo> | undefined = {}) : void {
    writer.writeStringValue("download_status", jobVideo.download_status);
    writer.writeStringValue("import_status", jobVideo.import_status);
    writer.writeStringValue("youtube_id", jobVideo.youtube_id);
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
export function serializeListJobResponse(writer: SerializationWriter, listJobResponse: Partial<ListJobResponse> | undefined = {}) : void {
    writer.writeStringValue("id", listJobResponse.id);
    writer.writeNumberValue("limit", listJobResponse.limit);
    writer.writeStringValue("search_query", listJobResponse.search_query);
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
export function serializePicture(writer: SerializationWriter, picture: Partial<Picture> | undefined = {}) : void {
    writer.writeStringValue("blob_id", picture.blob_id);
    writer.writeStringValue("id", picture.id);
    writer.writeStringValue("youtube_id", picture.youtube_id);
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
export function serializeResponse(writer: SerializationWriter, response: Partial<Response> | undefined = {}) : void {
    writer.writeCollectionOfObjectValues<Picture>("pictures", response.pictures, serializePicture);
    writer.writeNumberValue("total", response.total);
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
export function serializeUpdateJobLimitRequestBody(writer: SerializationWriter, updateJobLimitRequestBody: Partial<UpdateJobLimitRequestBody> | undefined = {}) : void {
    writer.writeNumberValue("limit", updateJobLimitRequestBody.limit);
}
export interface UpdateJobLimitRequestBody extends Parsable {
    /**
     * The limit property
     */
    limit?: number;
    /**
     * A URL to the JSON Schema for this object.
     */
    schema?: string;
}
/* tslint:enable */
/* eslint-enable */
