/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { RestartRequestBuilderRequestsMetadata, type RestartRequestBuilder } from './restart/';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/jobs/{id}/actions
 */
export interface ActionsRequestBuilder extends BaseRequestBuilder<ActionsRequestBuilder> {
    /**
     * The restart property
     */
    get restart(): RestartRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ActionsRequestBuilderUriTemplate = "{+baseurl}/api/jobs/{id}/actions";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ActionsRequestBuilderNavigationMetadata: Record<Exclude<keyof ActionsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    restart: {
        requestsMetadata: RestartRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
