// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: blob.sql

package db_sql

import (
	"context"
)

const addBlob = `-- name: AddBlob :one
INSERT into blob_storage
    (id, path)
    VALUES (?, ?)
RETURNING id, path
`

type AddBlobParams struct {
	ID   string
	Path string
}

func (q *Queries) AddBlob(ctx context.Context, arg AddBlobParams) (BlobStorage, error) {
	row := q.db.QueryRowContext(ctx, addBlob, arg.ID, arg.Path)
	var i BlobStorage
	err := row.Scan(&i.ID, &i.Path)
	return i, err
}

const getBlob = `-- name: GetBlob :one
SELECT path from blob_storage
    WHERE id = ?
`

func (q *Queries) GetBlob(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getBlob, id)
	var path string
	err := row.Scan(&path)
	return path, err
}
