// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: job.sql

package db_sql

import (
	"context"
	"database/sql"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
  id, search_query, "limit"
) VALUES (
  ?, ?, ?
)
RETURNING id, search_query, "limit"
`

type CreateJobParams struct {
	ID          string
	SearchQuery sql.NullString
	Limit       sql.NullInt64
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, createJob, arg.ID, arg.SearchQuery, arg.Limit)
	var i Job
	err := row.Scan(&i.ID, &i.SearchQuery, &i.Limit)
	return i, err
}

const listJobsWithProgress = `-- name: ListJobsWithProgress :many
SELECT jobs.id, search_query, "limit", yt_videos.id, job_id, status, error, blob_storage_id, "foreign" FROM jobs
LEFT JOIN yt_videos ON jobs.id = yt_videos.job_id
`

type ListJobsWithProgressRow struct {
	ID            string
	SearchQuery   sql.NullString
	Limit         sql.NullInt64
	ID_2          sql.NullString
	JobID         sql.NullString
	Status        sql.NullString
	Error         sql.NullString
	BlobStorageID sql.NullString
	Foreign       interface{}
}

func (q *Queries) ListJobsWithProgress(ctx context.Context) ([]ListJobsWithProgressRow, error) {
	rows, err := q.db.QueryContext(ctx, listJobsWithProgress)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJobsWithProgressRow
	for rows.Next() {
		var i ListJobsWithProgressRow
		if err := rows.Scan(
			&i.ID,
			&i.SearchQuery,
			&i.Limit,
			&i.ID_2,
			&i.JobID,
			&i.Status,
			&i.Error,
			&i.BlobStorageID,
			&i.Foreign,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
