// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: picture.sql

package db_sql

import (
	"context"
	"database/sql"
)

const addPicture = `-- name: AddPicture :one
INSERT into pictures
    (id, yt_video_id, frame_number, blob_storage_id)
    VALUES (?,?,?,?)
RETURNING id, yt_video_id, frame_number, blob_storage_id, "foreign"
`

type AddPictureParams struct {
	ID            string
	YtVideoID     sql.NullString
	FrameNumber   sql.NullInt64
	BlobStorageID sql.NullString
}

func (q *Queries) AddPicture(ctx context.Context, arg AddPictureParams) (Picture, error) {
	row := q.db.QueryRowContext(ctx, addPicture,
		arg.ID,
		arg.YtVideoID,
		arg.FrameNumber,
		arg.BlobStorageID,
	)
	var i Picture
	err := row.Scan(
		&i.ID,
		&i.YtVideoID,
		&i.FrameNumber,
		&i.BlobStorageID,
		&i.Foreign,
	)
	return i, err
}
